name: animate_to
description: Animates widgets to a target widget as an overlay
version: 0.1.0
homepage: 'https://github.com/Milad-Akarie/animate_to.git'

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
